force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/HQ_Phone__c.field-meta.xml
<CustomField>
    <fullName>HQ_Phone__c</fullName>
    <label>HQ Phone</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company__c/fields/LinkedIn__c.field-meta.xml
<CustomField>
    <fullName>LinkedIn__c</fullName>
    <label>LinkedIn</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/DefaultLeadHelper.cls
public without sharing class DefaultLeadHelper {
    public static Id checkForCompany(Lead Leaddata) {
        Id companyID;
        try{
            Company__c[] Companyrecord = [select Name,Id from Company__c where Name=:Leaddata.Company limit 1];
            if(Companyrecord.size() > 0){
                companyID = Companyrecord[0].Id;
            }else{
                Company__c companyobj   = new Company__c();
                companyobj.Name      = Leaddata.Company;
                //companyobj.HQ_Phone__c  = Leaddata.MobilePhone;
                insert companyobj;
                companyID = companyobj.Id;
            }
        }
        catch (Exception e) {
        }
        return companyID;
    }
    public static boolean checkForEmail(string emailID,id leadID) {
        boolean emailvalidate;
        try{
            lead[] emailArr = [select Id from Lead where Email=:emailID and id !=:leadID];
            if(emailArr.size() > 0){
                emailvalidate = true;
            }
        }
        catch (Exception e) {
        }
        return emailvalidate;
    }
    public static boolean checkForEmailLinkedIn(string emailID,string LinkedIn,id leadID) {
        boolean emaillinkedinvalidate;
        try{
            lead[] emailArr = [select Id from Lead where Email=:emailID and LinkedIn__c=:LinkedIn and id !=:leadID];
            if(emailArr.size() > 0){
                emaillinkedinvalidate = true;
            }else{
                emaillinkedinvalidate = false; 
            }
        }
        catch (Exception e) {
        }
        return emaillinkedinvalidate;
    }
    
    public static boolean checkForEmailNewRecord(string emailID) {
        boolean emailvalidate;
        try{
            lead[] emailArr = [select Id from Lead where Email=:emailID];
            if(emailArr.size() > 0){
                emailvalidate = true;
            }
        }
        catch (Exception e) {
        }
        return emailvalidate;
    }
    public static boolean checkForEmailLinkedInNewRecord(string emailID,string LinkedIn) {
        boolean emaillinkedinvalidate;
        try{
            lead[] emailArr = [select Id from Lead where Email=:emailID and LinkedIn__c=:LinkedIn];
            if(emailArr.size() > 0){
                emaillinkedinvalidate = true;
            }else{
                emaillinkedinvalidate = false; 
            }
        }
        catch (Exception e) {
        }
        return emaillinkedinvalidate;
    }
}